"""create initial tables

Revision ID: de7b1bc84007
Revises: 
Create Date: 2025-11-24 00:20:28.331230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7b1bc84007'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fires',
    sa.Column('fire_id', sa.Integer(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('coal_type', sa.String(length=10), nullable=False),
    sa.Column('pile_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('weight_act', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fire_start_date', sa.Date(), nullable=False),
    sa.Column('fire_end_date', sa.Date(), nullable=True),
    sa.Column('pile_formation_start', sa.Date(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('fire_id')
    )
    op.create_index('idx_fires_composite', 'fires', ['warehouse_id', 'pile_id', 'fire_start_date'], unique=False)
    op.create_index(op.f('ix_fires_fire_id'), 'fires', ['fire_id'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('pile_id', sa.Integer(), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index('idx_predictions_composite', 'predictions', ['warehouse_id', 'pile_id', 'prediction_date', 'forecast_date'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_id'), 'predictions', ['prediction_id'], unique=False)
    op.create_table('supplies',
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('unloading_date', sa.Date(), nullable=False),
    sa.Column('coal_type', sa.String(length=50), nullable=False),
    sa.Column('pile_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('loading_ship_date', sa.Date(), nullable=True),
    sa.Column('to_warehouse_ton', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('to_ship_ton', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('supply_id')
    )
    op.create_index('idx_supplies_composite', 'supplies', ['warehouse_id', 'pile_id', 'unloading_date'], unique=False)
    op.create_index(op.f('ix_supplies_supply_id'), 'supplies', ['supply_id'], unique=False)
    op.create_table('temperatures',
    sa.Column('temperature_id', sa.Integer(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('pile_id', sa.Integer(), nullable=False),
    sa.Column('coal_type', sa.String(length=50), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('picket', sa.String(length=50), nullable=True),
    sa.Column('shift', sa.Integer(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('temperature_id')
    )
    op.create_index('idx_temperatures_composite', 'temperatures', ['warehouse_id', 'pile_id', 'measurement_date'], unique=False)
    op.create_index('idx_temperatures_temp', 'temperatures', ['temperature'], unique=False)
    op.create_index(op.f('ix_temperatures_temperature_id'), 'temperatures', ['temperature_id'], unique=False)
    op.create_table('weather',
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('air_temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('temp_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('wind_speed_avg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_speed_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('precipitation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('weather_id'),
    sa.UniqueConstraint('date')
    )
    op.create_index('idx_weather_date', 'weather', ['date'], unique=False)
    op.create_index(op.f('ix_weather_weather_id'), 'weather', ['weather_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_weather_id'), table_name='weather')
    op.drop_index('idx_weather_date', table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_temperatures_temperature_id'), table_name='temperatures')
    op.drop_index('idx_temperatures_temp', table_name='temperatures')
    op.drop_index('idx_temperatures_composite', table_name='temperatures')
    op.drop_table('temperatures')
    op.drop_index(op.f('ix_supplies_supply_id'), table_name='supplies')
    op.drop_index('idx_supplies_composite', table_name='supplies')
    op.drop_table('supplies')
    op.drop_index(op.f('ix_predictions_prediction_id'), table_name='predictions')
    op.drop_index('idx_predictions_composite', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_fires_fire_id'), table_name='fires')
    op.drop_index('idx_fires_composite', table_name='fires')
    op.drop_table('fires')
    # ### end Alembic commands ###
