"""remove coal_type from temperatures

Revision ID: ef1793dda181
Revises: de7b1bc84007
Create Date: 2025-11-24 05:23:28.771722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1793dda181'
down_revision: Union[str, Sequence[str], None] = 'de7b1bc84007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temperatures', 'coal_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperatures', sa.Column('coal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
